name: diplomatik_app
description: Diplomatik smartphone applicatie
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.5+1
  http: ^0.12.0+4
  json_annotation: ^3.1.1

dev_dependencies:
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true

